CREATE TABLE articles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  source text NOT NULL CHECK (source IN ('bbc', 'the_conversation')),
  source_url text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  title_original text,
  title_tr text,
  excerpt_original text,
  excerpt_tr text,
  content_original text,
  content_tr text,
  content_hash text NOT NULL,
  featured_image_url text,
  featured_image_source_url text,
  image_credit text,
  category_slug text REFERENCES categories(slug) ON DELETE SET NULL,
  region_slug text REFERENCES regions(slug) ON DELETE SET NULL,
  published_at timestamptz NOT NULL,
  scraped_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  author_original text,
  reading_time_minutes integer GENERATED ALWAYS AS (GREATEST(1, length(coalesce(content_tr, '')) / 1500)) STORED,
  view_count integer NOT NULL DEFAULT 0,
  is_featured boolean NOT NULL DEFAULT false
);
