CREATE TABLE sectors (
  slug text PRIMARY KEY,
  name_tr text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_dropdown_featured boolean NOT NULL DEFAULT false
);

INSERT INTO sectors (slug, name_tr, display_order, is_dropdown_featured) VALUES
  ('insaat-muteahhitlik',       'İnşaat & Müteahhitlik',        1,  true),
  ('enerji',                    'Enerji',                       2,  true),
  ('savunma-sanayi',            'Savunma Sanayi',               3,  true),
  ('madencilik',                'Madencilik',                   4,  true),
  ('tekstil-hazir-giyim',       'Tekstil & Hazır Giyim',        5,  true),
  ('kozmetik-hijyen',           'Kozmetik & Hijyen',            6,  true),
  ('demir-celik-sanayi',        'Demir-Çelik & Sanayi',         7,  true),
  ('tarim-gida',                'Tarım & Gıda',                 8,  true),
  ('otomotiv',                  'Otomotiv',                     9,  true),
  ('ambalaj-geri-donusum',      'Ambalaj & Geri Dönüşüm',       10, false),
  ('bankacilik-finans',         'Bankacılık & Finans',          11, false),
  ('beyaz-esya-ev-aletleri',    'Beyaz Eşya & Ev Aletleri',     12, false),
  ('cimento-insaat-malzemeleri','Çimento & İnşaat Malzemeleri', 13, false),
  ('ev-tekstili-hali',          'Ev Tekstili & Halı',           14, false),
  ('fintech-dijital-odeme',     'Fintech & Dijital Ödeme',      15, false),
  ('fuarcilik-etkinlik',        'Fuarcılık & Etkinlik',         16, false),
  ('gayrimenkul-konut',         'Gayrimenkul & Konut',          17, false),
  ('havacilik-sivil-havacilik', 'Havacılık & Sivil Havacılık',  18, false),
  ('hvac-r',                    'HVAC-R (Isıtma-Soğutma)',      19, false),
  ('ilac-tibbi-cihaz',          'İlaç & Tıbbi Cihaz',           20, false),
  ('kimya-petrokimya',          'Kimya & Petrokimya',           21, false),
  ('lojistik-tasimaci',         'Lojistik & Taşımacılık',       22, false),
  ('makine-yedek-parca',        'Makine & Yedek Parça',         23, false),
  ('mobilya-dekorasyon',        'Mobilya & Dekorasyon',         24, false),
  ('perakende-e-ticaret',       'Perakende & E-ticaret',        25, false),
  ('saglik-saglik-turizmi',     'Sağlık & Sağlık Turizmi',      26, false),
  ('teknoloji-yazilim',         'Teknoloji & Yazılım',          27, false),
  ('telekomunikasyon',          'Telekomünikasyon',              28, false),
  ('turizm-otelcilik',          'Turizm & Otelcilik',           29, false),
  ('yenilenebilir-enerji',      'Yenilenebilir Enerji',         30, false),
  ('diger-sektor',              'Diğer',                        31, false);
